services:
  app:
    image: react-notes-server
    build:
      context: .
      secrets:
        - react_app_env
        - server_env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    user: postgres
    secrets:
      - postgres_password
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/psql_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  react_app_env:
    file: secrets/react_app.env
  server_env:
    file: secrets/server.env
  postgres_password:
    file: secrets/postgres_password
