version: '0.3.0'

services:
  server:
    image: olsonadr/react-notes
    container_name: react-notes-server
    build:
      context: .
    secrets:
      - postgres_password
    environment:
      - NODE_ENV=production
      - POSTGRES_DB=notes
      - POSTGRES_USER=postgres
      - POSTGRES_SERVER=react-notes-db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_SSL=false
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:9.6.2-alpine
    container_name: react-notes-db
    restart: always
    user: postgres
    secrets:
      - postgres_password
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/psql_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  postgres_password:
    file: secrets/postgres_password
